use_frameworks!

target 'YJFImageLooper_Example' do
 
    pod 'YJFImageLooper', :path => '../'

    pod 'SDWebImage', '~> 4.1.0'
    
    

  target 'YJFImageLooper_Tests' do
    inherit! :search_paths

    
  end
end
